version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laptop_chatbot_app
    ports:
      - "8080:8080"
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped

